# publish_release.ps1 - stamp a built KenshiCoop.dll as a release and write the
# manifest the in-DLL updater reads.
#
# The updater compares COOP_BUILD_VERSION (baked into the DLL, src/netproto/Wire.h)
# against `version=` in dist/UPDATE.txt on the release branch. Those two MUST agree
# or every client re-downloads the same build forever, so this script reads the
# version out of Wire.h rather than taking it as an argument.
#
# Usage (from the repo root, after scripts\build_plugin.cmd Release):
#   powershell -ExecutionPolicy Bypass -File scripts\publish_release.ps1
#   powershell ... -Owner you -Repo KenshiCoop        # first run, or to change it
#   powershell ... -WhatIf                            # print, write nothing
#
# It does NOT push or create the GitHub release - it prints the two commands to
# run, so nothing leaves the machine without you typing it.

[CmdletBinding()]
param(
    [string]$Owner,
    [string]$Repo,
    [string]$Dll    = "src\plugin\x64\Release\KenshiCoop.dll",
    [string]$Out    = "dist\UPDATE.txt",
    [string]$Notes  = "",
    [switch]$WhatIf
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

# --- version + protocol straight out of the header the DLL was built from -----
$wire = Get-Content 'src\netproto\Wire.h' -Raw
if ($wire -notmatch 'COOP_BUILD_VERSION\s*=\s*"([^"]+)"') {
    throw "COOP_BUILD_VERSION not found in src/netproto/Wire.h"
}
$version = $Matches[1]
if ($wire -notmatch 'PROTOCOL_VERSION\s*=\s*(\d+)') {
    throw "PROTOCOL_VERSION not found in src/netproto/Wire.h"
}
$proto = $Matches[1]

if (-not (Test-Path $Dll)) { throw "No DLL at $Dll - run scripts\build_plugin.cmd Release first" }
$dllItem = Get-Item $Dll

# A DLL older than the header means the version string in it is not $version.
$wireItem = Get-Item 'src\netproto\Wire.h'
if ($dllItem.LastWriteTime -lt $wireItem.LastWriteTime) {
    throw "$Dll is older than Wire.h - rebuild before publishing, or the DLL carries a different COOP_BUILD_VERSION than this manifest claims"
}

$sha = (Get-FileHash $Dll -Algorithm SHA256).Hash.ToLower()

# --- owner/repo: remembered in the manifest so repeat runs need no arguments ---
if (-not $Owner -or -not $Repo) {
    if (Test-Path $Out) {
        $prev = Get-Content $Out -Raw
        if (-not $Owner -and $prev -match '(?m)^\s*url\s*=\s*https://github\.com/([^/]+)/([^/]+)/') {
            $Owner = $Matches[1]; $Repo = $Matches[2]
        }
    }
}
if (-not $Owner -or -not $Repo) {
    throw "First run needs -Owner <github account> -Repo <repository> (they are remembered in $Out afterwards)"
}

$tag = "v$version"
$url = "https://github.com/$Owner/$Repo/releases/download/$tag/KenshiCoop.dll"

$manifest = @"
# KenshiCoop update manifest - read by the in-DLL updater over HTTPS.
# Generated by scripts/publish_release.ps1; do not hand-edit sha256.
version=$version
proto=$proto
sha256=$sha
url=$url
notes=$Notes
"@

Write-Host ""
Write-Host "  version   $version   (proto $proto)"
Write-Host "  dll       $($dllItem.Length) bytes, built $($dllItem.LastWriteTime)"
Write-Host "  sha256    $sha"
Write-Host "  url       $url"
Write-Host ""

if ($WhatIf) { Write-Host "-WhatIf: not writing $Out"; Write-Host $manifest; exit 0 }

New-Item -ItemType Directory -Force -Path (Split-Path $Out) | Out-Null
[IO.File]::WriteAllText((Join-Path $root $Out), $manifest -replace "`r`n", "`n")
Write-Host "wrote $Out"
Write-Host ""
Write-Host "Next, in order (the manifest must not go live before the asset it names):"
Write-Host "  1. gh release create $tag `"$Dll`" --title `"$tag`" --notes `"$Notes`""
Write-Host "  2. git add $Out && git commit -m `"release $tag`" && git push"
Write-Host ""
Write-Host "Order matters: clients read the manifest first and download the url it"
Write-Host "names. Pushing the manifest before the release asset exists gives every"
Write-Host "player a failed download until step 1 lands."
